id: P5A75C4CD
initial_creation_type: input
source_metadata:
  title: Dudjom Rinpoche Series
  language: es
  description: 'We present the following texts by Kyabje Dudjom Rinpoche Jikdral Yeshe
    Dorje (bdud ''joms ''jigs bral ye shes rdo rje, 1904–1987), the renowned yogi
    and scholar and first appointed head of the Nyingma school in exile:'
  volume:
    77bc9dd30c314231ac8fbb2b627c7b83:
      title: The Mirror Clearly Showing What to Adopt and Abandon
      parent: Advice
    47df06e5132845968e135e32b1c73003:
      title: The Concise Benefits of the Festival of the Tenth Day
      parent: Benefits
    127bbff4fa6449fab96bd2f3c21466b1:
      title: 'The Light of Primordial Wisdom: An Instruction Manual for the Primordially
        Pure Perfection Stage of the Powerful & Wrathful Dorje Drolö, Conqueror of
        Demons'
      parent: Commentaries
    45e899437e5648d28b37e0b5d20c44e6:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    a85a810604cf48478fc96542c77cb164:
      title: Concise Consecration
      parent: Consecration
    7155369290d1430a93974b54e2c8f32d:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Dharma Protectors
    3a5290ecb4de4e478202797f268df7fc:
      title: Dzogchen Aspiration Prayer
      parent: Dzogchen
    fb8b473fa0d34fd6979b5e022968a7bb:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Dzogchen
    5b5c04c267264ba08179bb484b67929f:
      title: Summary of Striking the Vital Point in Three Statements
      parent: Dzogchen
    a8fa94c288bf4a16940ef8ecb2783b7c:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Guru Rinpoche Prayers
    ce8123f4be28481bb802409b09a1abc7:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Guru Rinpoche Prayers
    99f3cc8ae1c3477fac95f2b129afec34:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Guru Rinpoche Prayers
    3b81e2ab56484377a2c3df0ce0081f0e:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Guru Rinpoche Prayers
    4ecc9ecf73da4befbfe634aa8e631ec2:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Guru Rinpoche Prayers
    520bf49a408a4d7f9e2c94f5151274f0:
      title: A Concise Lineage Prayer
      parent: Lineage Prayers
    7c89c2d073094b1ca182f653da55f372:
      title: Prayer for the Long Life Dodrupchen Rinpoche
      parent: Long Life Prayers
    aa77bcad7320448793ce105b98c581c1:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    52eb4c27733243cc9b01c2fa2757234f:
      title: Prayer for the Long Life of Dzogchen Rinpoche
      parent: Long Life Prayers
    f3c80d50507c4c41862310aae7f605cf:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    1e3fbb9434534370ab4e102dd07d3734:
      title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great
        Tertön Dudjom Jigdral Yeshe Dorje'
      parent: Long Life Prayers
    2ea6728d338148da854492bf10388882:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Ngöndro
    afe6ccd3f0b4476bbd727dc7941fc181:
      title: Brief Notes on the Visualization for the Concise Recitation of the Pure
        Vision Preliminary Practice
      parent: Ngöndro
    fcaac9667cda4945b468a1c861ab3408:
      title: Brief Red Sur Offering
      parent: Offering
    97c0d2225ee74508b4bfde2dd63bac40:
      title: Brief Sur Offering
      parent: Offering
    612e3b14e1b84251a1c7232fec8e29f4:
      title: A Prayer to Recognize My Own Faults and Keep in Mind the Objects of Refuge
      parent: Prayers
    dbc673cf29ac40a688187f08aa1ae26e:
      title: Essence and Embodiment of All the Buddhas
      parent: Prayers
    904df620f369453d97c7836c6b76c8dc:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Prayers
    72adede975f94b2ea57d090b2c606c51:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Sādhanas
    5f5cb1d327ba4f52bc2fb27740012667:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    442dcbea6b9a4dfd86437e203d598baa:
      title: A Daily Practice of Lama Sangdü
      parent: Sādhanas
    f2e09a8840f34d708a95ae158e8dd9c8:
      title: A Daily Practice of Ucchuṣma
      parent: Sādhanas
    c7ac41c21c844461a839b351ef26e6b5:
      title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of
        Immortality
      parent: Sādhanas
    08e2d218211a4263a8ea770268441149:
      title: Daily Practice of Dorje Gotrab
      parent: Sādhanas
    783f5ab335564588a139446282bddd57:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sādhanas
    a471db5455b5484e8ddd37fff2b53233:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      parent: Sādhanas
    d70c9a2a948544438e36a8fc23781e1f:
      title: The Daily Practice of the Secret Sādhana of Dorje Drolö
      parent: Sādhanas
    05398b0a800143308bc6b51e9cb5a456:
      title: The Essential Daily Practice of Vajrakīla
      parent: Sādhanas
    d667ae66f75443c28ce35d969c733f69:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
    e5c8062e7ac34fb6bee851fafa88c4b4:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Sang Offering
    b4e4ea293f4e4345a3610f23968cb048:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Sang Offering
    4c79834dbabd435e85ba53b0eb157128:
      title: 'The Concentrated Essence: A Concise Practice of Healing and Purifying
        (Sojong) the Three Sets of Vows'
      parent: Sojong
    6b2170a9afdb4a33a11e8c9caacd557a:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Tsok
    563f36c121ec4c6abf03c545a9f67798:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Tsok
    0180771346a34f4c8afd2aed0bb1d4fd:
      title: A Daily Practice of Vajraṇakhī
      parent: Vajraṇakhī
created_at: '2022-02-28T23:10:30.050230'
last_modified_at: '2022-02-28T23:10:30.050233'
